apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "aksdeploy"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "aksdeploy"
    spec:
      containers:
        - name: "aksdeploy"
          image: "cijenregistry.azurecr.io/aksdeploy"
          ports:
          - containerPort: 80