---
# Source: mychart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment1
  labels:
    app: custom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      annotations:
        rollme: "T168e"
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: registry.gitlab.com/vinaykadalagi1/cijen/custom-image:1.16.0
        imagePullPolicy: Always
